server:
  port: 8080
spring:
  application:
    name: investment-api
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # Interface H2 Console para debug (opcional)
  h2:
    console:
      enabled: true
      path: /h2-console

  # Configurações do JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
