package com.wallet.investmenthistory.domain;

import com.wallet.investmenthistory.service.BigDecimalUtil;

import java.math.BigDecimal;

public class Stock {
    //    TICKER;
    private String ticker;
    //    PRECO;
    private BigDecimal preco;
    //    DY;
    private BigDecimal dividendYield;
    //    P/L;
    private BigDecimal pL;
    //    P/VP;
    private BigDecimal pVP;
    //    P/ATIVOS;
    private BigDecimal pAtivos;
    //    MARGEM BRUTA;
    private BigDecimal margemBruta;
    //    MARGEM EBIT;
    private BigDecimal margemEbit;
    //    MARG. LIQUIDA;
    private BigDecimal margemLiquida;
    //    P/EBIT;
    private BigDecimal pEbit;
    //    EV/EBIT;
    private BigDecimal evEbit;
    //    DIVIDA LIQUIDA / EBIT;
    private BigDecimal dividaLiquidaEbit;
    //    DIV. LIQ. / PATRI.;
    private BigDecimal DivLiqPatri;
    //    PSR;
    private BigDecimal pSR;
    //    P/CAP. GIRO;
    private BigDecimal pCapGiro;
    //    P. AT CIR. LIQ.;
    private BigDecimal pAtCirLiq;
    //    LIQ. CORRENTE;
    private BigDecimal liqCorrente;
    //    ROE;
    private BigDecimal rOE;
    //    ROA;
    private BigDecimal rOA;
    //    ROIC;
    private BigDecimal rOIC;
    //    PATRIMONIO / ATIVOS;
    private BigDecimal patrimonioAtivos;
    //    PASSIVOS / ATIVOS;
    private BigDecimal passivosAtivos;
    //    GIRO ATIVOS;
    private BigDecimal giroAtivos;
    //    CAGR RECEITAS 5 ANOS;
    private BigDecimal cAGRReceitas5Anos;
    //    CAGR LUCROS 5 ANOS;
    private BigDecimal cAGRLucros5Anos;
    //    LIQUIDEZ MEDIA DIARIA;
    private BigDecimal liquidezMediaDiaria;
    //    VPA;
    private BigDecimal vPA;
    //    LPA;
    private BigDecimal lPA;
    //    PEG Ratio;
    private BigDecimal pegRatio;
    //    VALOR DE MERCADO;
    private BigDecimal valorDeMercado;

    public Stock(String[] cols) {
        this.ticker = cols[0];
        this.preco = BigDecimalUtil.readValue(cols[1]);
        this.dividendYield = BigDecimalUtil.readValue(cols[2]);
        this.pL = BigDecimalUtil.readValue(cols[3]);
        this.pVP = BigDecimalUtil.readValue(cols[4]);
        this.pAtivos = BigDecimalUtil.readValue(cols[5]);
        this.margemBruta = BigDecimalUtil.readValue(cols[6]);
        this.margemEbit = BigDecimalUtil.readValue(cols[7]);
        this.margemLiquida = BigDecimalUtil.readValue(cols[8]);
        this.pEbit = BigDecimalUtil.readValue(cols[9]);
        this.evEbit = BigDecimalUtil.readValue(cols[10]);
        this.dividaLiquidaEbit = BigDecimalUtil.readValue(cols[11]);
        this.DivLiqPatri = BigDecimalUtil.readValue(cols[12]);
        this.pSR = BigDecimalUtil.readValue(cols[13]);
        this.pCapGiro = BigDecimalUtil.readValue(cols[14]);
        this.pAtCirLiq = BigDecimalUtil.readValue(cols[15]);
        this.liqCorrente = BigDecimalUtil.readValue(cols[16]);
        this.rOE = BigDecimalUtil.readValue(cols[17]);
        this.rOA = BigDecimalUtil.readValue(cols[18]);
        this.rOIC = BigDecimalUtil.readValue(cols[19]);
        this.patrimonioAtivos = BigDecimalUtil.readValue(cols[20]);
        this.passivosAtivos = BigDecimalUtil.readValue(cols[21]);
        this.giroAtivos = BigDecimalUtil.readValue(cols[22]);
        this.cAGRReceitas5Anos = BigDecimalUtil.readValue(cols[23]);
        this.cAGRLucros5Anos = BigDecimalUtil.readValue(cols[24]);
        this.liquidezMediaDiaria = BigDecimalUtil.readValue(cols[25]);
        this.vPA = BigDecimalUtil.readValue(cols[26]);
        this.lPA = BigDecimalUtil.readValue(cols[27]);
        this.pegRatio = BigDecimalUtil.readValue(cols[28]);
        this.valorDeMercado = BigDecimalUtil.readValue(cols[29]);
    }
}
