server:
  port: 8081
spring:
  application:
    name: authuser
  datasource:
    url: jdbc:postgresql://localhost:5432/authuser_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true