CREATE TABLE tb_stock
(
    id                     SERIAL PRIMARY KEY,
    ticker                 VARCHAR(10) NOT NULL,
    preco                  NUMERIC,
    dy                     NUMERIC,
    pl                     NUMERIC,
    p_vp                   NUMERIC,
    p_ativos               NUMERIC,
    margem_bruta           NUMERIC,
    margem_ebit            NUMERIC,
    marg_liquida           NUMERIC,
    p_ebit                 NUMERIC,
    ev_ebit                NUMERIC,
    divida_liquida_ebit    NUMERIC,
    div_liquida_patrimonio NUMERIC,
    psr                    NUMERIC,
    p_cap_giro             NUMERIC,
    p_at_cir_liq           NUMERIC,
    liq_corrente           NUMERIC,
    roe                    NUMERIC,
    roa                    NUMERIC,
    roic                   NUMERIC,
    patrimonio_ativos      NUMERIC,
    passivos_ativos        NUMERIC,
    giro_ativos            NUMERIC,
    cagr_receitas_5_anos   NUMERIC,
    cagr_lucros_5_anos     NUMERIC,
    liquidez_media_diaria  NUMERIC,
    vpa                    NUMERIC,
    lpa                    NUMERIC,
    peg_ratio              NUMERIC,
    valor_mercado          NUMERIC
);

CREATE TABLE tb_real_state_fund
(
    id                     SERIAL PRIMARY KEY,
    ticker                 VARCHAR(10) NOT NULL,
    preco                  NUMERIC,
    ultimo_dividendo       NUMERIC,
    dy                     NUMERIC,
    valor_patrimonial_cota NUMERIC,
    p_vp                   NUMERIC,
    liquidez_media_diaria  NUMERIC,
    percentual_em_caixa    NUMERIC,
    cagr_dividendos_3_anos NUMERIC,
    cagr_valor_cota_3_anos NUMERIC,
    patrimonio             NUMERIC,
    n_cotistas             NUMERIC,
    gestao                 VARCHAR(50),
    n_cotas                NUMERIC
);