spring:
  application:
    name: cash-control
  datasource:
    url: jdbc:postgresql://localhost:5432/cash_control_db
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081
