### Criando uma renda
POST http://localhost:8081/api/incomes
Content-Type: application/json

{
  "name": "Dividendo",
  "incomeType": "PASSIVE_INCOME",
  "userId": "8ca161e7-a3d6-4275-9193-32a7adfdb9a6",
  "description": "ACOES"
}

###

GET http://localhost:8081/api/incomes?userId=8ca161e7-a3d6-4275-9193-32a7adfdb9a6
Accept: application/json

###

###

GET http://localhost:8081/api/incomes/receives?userId=8ca161e7-a3d6-4275-9193-32a7adfdb9a6
Accept: application/json

###

###
POST http://localhost:8081/api/incomes/1/receives
Content-Type: application/json

{
  "projected": 0.0,
  "actual": 0.0,
  "date": "2024-05-15",
  "description": "description"
}

###